apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-chunks
  namespace: monitoring
  labels:
    app: loki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
