apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      app: loki
      app.kubernetes.io/instance: prod
      environment: production
    includeSelectors: false
patches:
  - patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: loki-chunks
        namespace: monitoring
      spec:
        resources:
          requests:
            storage: 10Gi
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: loki
        namespace: monitoring
      spec:
        template:
          spec:
            containers:
              - name: loki
                resources:
                  requests:
                    cpu: 200m
                    memory: 256Mi
                  limits:
                    cpu: 500m
                    memory: 512Mi
