apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: default
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.2.0
